version: "2"

# Related repos must be installed under the same parent as this repo.
# sd-api: https://github.com/StartingDreams/sd-api
# sd-frontend: https://github.com/StartingDreams/sd-frontend
# sd-nginx: https://github.com/StartingDreams/sd-nginx
# sd-mongo: https://github.com/StartingDreams/sd-mongo
# sd-redis: https://github.com/StartingDreams/sd-redis

services:

  api:
    container_name: api
    env_file: .env
    build:
      context: ../sd-api
    volumes:
      - ../sd-api/src:/var/www/html
    depends_on:
      - mongo
    networks:
      - backend-net

  frontend:
    container_name: frontend
    env_file: .env
    build:
      context: ../sd-frontend
    volumes:
      - ../sd-frontend:/var/www
    depends_on:
      - mongo
    networks:
      - backend-net

  nginx:
    container_name: nginx
    env_file: .env
    build:
      context: ../sd-nginx
    #command: /bin/bash -c "envsubst '\$HTTP_PORT \$HTTPS_PORT' < /etc/nginx/conf.d/default.conf.tmpl > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - frontend
      - api
    networks:
      - frontend-net
      - backend-net

  mongo:
    container_name: mongo
    env_file: .env
    build:
      context: ../sd-mongo
    volumes:
      - ../sd-mongo/data/:/data/db
    networks:
      - backend-net


networks:
  backend-net:
    driver: bridge
  frontend-net:
    driver: bridge
