version: "2"

# Related repos must be installed under the same parent as this repo.
# sd-frontend: https://github.com/StartingDreams/sd-frontend
# sd-mongo: https://github.com/StartingDreams/sd-mongo
# sd-redis: https://github.com/StartingDreams/sd-redis


services:

  api:
    container_name: api
    env_file: .env
    build:
      context: ../sd-api
    volumes:
      - ../sd-api/src:/var/www/html
    ports:
      - "30081:80"
      - "30444:443"
    depends_on:
      - mongo
    networks:
      - backend

  frontend:
    container_name: frontend
    env_file: .env
    build:
      context: ../sd-frontend
    volumes:
      - ../sd-frontend:/var/www
    ports:
      - "30080:30080"
      - "30443:30443"
    depends_on:
      - mongo
    networks:
      - backend

  nginx:
    container_name: nginx
    env_file: .env
    build:
      context: ../sd-nginx
    #command: /bin/bash -c "envsubst '\$HTTP_PORT \$HTTPS_PORT' < /etc/nginx/conf.d/default.conf.tmpl > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - "8080"
      - "8443"
    depends_on:
      - frontend
      - api
    networks:
      - frontend
      - backend

  mongo:
    container_name: mongo
    env_file: .env
    build:
      context: ../sd-mongo
    volumes:
      - ../sd-mongo/data/:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend


networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
